### PR TITLE
artists page

### PR DESCRIPTION
**Pull request by cmd-kae**
this looks to resolve issue #8

it's currently sorting by whether or not an artist has a featured image since that's the only thing that will really mess up the design. it looks the same as the front page but instead of sorting by artist type it's sorting by the image.

### CODE REVIEW

**Comment by drewwestphal** [comment]
Looks great! 

/cc @paulnotstorm @gregstormd 

https://dev.jococruise.com/artists/

**Comment by drewwestphal** [comment]
I'd say though that for type "page" we don't need the bumper. For everything else, I think it's good.

**Comment by cmd-kae** [comment]
Oh, okay. Would you like it to be there but blank for visual consistency?

**Comment by drewwestphal** [comment]
Sure. Let's try that. It just seems weird to have the bumpers guiding you
to likely unrelated page.s

**Pull request merged**
