### PR TITLE
front-page about section

### PR DESCRIPTION
**Pull request by cmd-kae**
This is the exact same as the M&C section instead it has improved padding on the bottom and the image will fill the space instead of cutting off. If it looks okay to you, it'll work for M&C too as long as the font colors are updated.

### CODE REVIEW

**Comment by cmd-kae** [comment]
this looks to address issue: #8

**Comment by drewwestphal** [comment]
Ok! Thank you. I have merged and will be testing soon!

**Comment by drewwestphal** [comment]
Also note that I have made some minor changes to master which you should be able to merge into your branch, so you are working with the most up to date version

**Comment by cmd-kae** [comment]
Done!

**Pull request merged**
